# Generated by Django 5.2.5 on 2025-08-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Captcha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("captcha", models.CharField(max_length=4)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
